name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install robotframework robotframework-seleniumlibrary robotframework-requests

      - name: Run Tests
        run: |
          robot tests/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-reports
          path: report.html
